// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginView() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head><title>Ratt - Login</title><script src=\"https://cdn.tailwindcss.com\"></script><style>\n            @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@200;400;700&display=swap');\n\n            body, html {\n                min-height: 100vh;\n                margin: 0;\n                overflow-x: hidden;\n                font-family: 'Nunito', sans-serif;\n                box-sizing: border-box;\n            }\n            </style></head><body class=\"bg-slate-950 text-slate-50 flex items-center justify-center min-h-screen\"><form action=\"/login\" method=\"POST\" class=\"bg-slate-800 p-8 rounded-lg shadow-lg w-80\"><h1 class=\"text-2xl font-bold mb-6 text-center\">Login</h1><label for=\"username\" class=\"block mb-2 text-sm font-medium\">Email</label> <input type=\"text\" name=\"username\" required class=\"w-full px-4 py-2 mb-4 text-black rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500\"> <label for=\"password\" class=\"block mb-2 text-sm font-medium\">Password</label> <input type=\"password\" name=\"password\" required class=\"w-full px-4 py-2 mb-6 text-black rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500\"> <button type=\"submit\" class=\"w-full bg-blue-600 py-2 rounded-lg hover:bg-blue-700 font-bold\">Login</button></form></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
