apiVersion: apps/v1
kind: Deployment
metadata:
  name: valentine
  labels:
    app: valentine
spec:
  selector:
    matchLabels:
      app: valentine
  replicas: 1
  template:
    metadata:
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/path: /metrics
      #   prometheus.io/port: "8080"
      labels:
        app: valentine
    spec:
      containers:
        - name: valentine
          image: valentine
          env:
            - name: VALENTINE_PORT
              value: "3000"
          # livenessProbe:
          #   httpGet:
          #     path: /healthcheck
          #     port: 8081
      terminationGracePeriodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: valentine
  labels:
    app: valentine
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: valentine

