apiVersion: apps/v1
kind: Deployment
metadata:
  name: valentine
  labels:
    app: valentine
spec:
  selector:
    matchLabels:
      app: valentine
  replicas: 1
  template:
    metadata:
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/path: /metrics
      #   prometheus.io/port: "8080"
      labels:
        app: valentine
    spec:
      containers:
        - name: valentine
          image: valentine
          # livenessProbe:
          #   httpGet:
          #     path: /healthcheck
          #     port: 8081
      terminationGracePeriodSeconds: 300

