name: Generate code
description: Generate code for services
branding:
  icon: 'upload-cloud'
  color: 'red'

inputs:
  service:
    description: service parameter
    required: true

runs:
  using: composite
  steps:
    - name: Actions checkout
      uses: actions/checkout@v4

    - name: Generate code for tusk
      if: inputs.service == 'tusk' 
      uses: ./.github/actions/generate_code/tusk

    - name: Generate code for valentine
      if: inputs.service == 'valentine' 
      uses: ./.github/actions/generate_code/valentine
