name: Prepare services
description: Prepare services
branding:
  icon: 'upload-cloud'
  color: 'red'

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.1"

